### ISSUE TITLE
Clicking ... in the top-right doesn't seem to do anything

### ISSUE THREAD

**Issue by benui-dev** [Nebukam/mkfont#22]
Maybe I'm missing something but should something happen? I'm running Windows 10, mkfont 1.2.0

**Comment by Nebukam** [comment]
Ahahah yeah that's an artifact from the underlying framework : nothing is to be expected there.  
Thanks for the report, completely forgot about that 👍

**Comment by Nebukam** [comment]
No opens the app settings (_this was totally intended from the start_) 👌
